from typing import Any, Dict

class Pipeline:
    """Minimal stub for redis.client.Pipeline used by EpisodicMemory.

    This provides only the subset of methods referenced in the codebase. Extend
    as needed when additional Redis commands are used.
    """

    def hset(self, name: str, mapping: Dict[str, Any]) -> int: ...
    def expire(self, name: str, time: int) -> bool: ...
    def sadd(self, name: str, *values: Any) -> int: ...
    def execute(self) -> Any: ...
