from __future__ import annotations

import pytest

from pathlib import Path

from typer.testing import CliRunner

from ice_cli.cli import app


@pytest.mark.skip("Legacy 'ice sdk' commands removed - use 'ice create chain' instead")
def test_cli_chain_builder(tmp_path: Path) -> None:  # noqa: D401 – integration
    """`ice sdk create-chain --builder` should generate a valid .chain.py file."""

    runner = CliRunner()

    # Provide answers for chain meta + 1 tool node: persist?, type, name, (deps blank)
    answers = "y\ntool\necho_start\n \nn\ny\n"
    res = runner.invoke(
        app,
        [
            "sdk",
            "create-chain",
            "demo_chain",
            "--builder",
            "--nodes",
            "1",
            "--dir",
            str(tmp_path),
            "--force",
        ],
        input=answers,
    )

    assert res.exit_code == 0, res.stdout

    chain_file = tmp_path / "demo_chain.chain.py"
    assert chain_file.exists(), "Chain file not generated by builder"
