repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.6
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile=black"]
  # Temporarily remove mypy from pre-commit; enforce via deterministic Docker stage
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
  - repo: local
    hooks:
      - id: forbid-shadow-stubs
        name: forbid-shadow-stubs
        language: system
        pass_filenames: false
        entry: |
          bash -c '
          if [ -d typings ]; then
            if ls -1 typings | grep -E "^(fastapi|httpx|openai|structlog)$" >/dev/null 2>&1; then
              echo "ERROR: shadow stubs in ./typings. Remove them." >&2
              exit 1
            fi
          fi
          exit 0
          '
