repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.2
    hooks:
      - id: ruff
        args: ["--fix"]
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile=black"]
  # Pyright mirror temporarily disabled due to GitHub repo access issue
  - repo: https://github.com/seddonym/import-linter
    rev: v2.3
    hooks:
      - id: import-linter
  - repo: https://github.com/pypa/pip-audit
    rev: v2.7.2
    hooks:
      - id: pip-audit
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.402
    hooks:
      - id: pyright
        args: ["--warnings", "src"]
        stages: [manual]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: ["--strict", "--explicit-package-bases", "src"]
        stages: [manual]
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff (strict)
        entry: ruff check src
        language: system
        pass_filenames: false
        always_run: true
      - id: pytest
        name: pytest
        entry: pytest -q
        language: system
        pass_filenames: false
        always_run: true
      - id: coverage
        name: pytest (coverage gate)
        entry: pytest --cov=ice_sdk --cov=ice_orchestrator --cov-report=term --cov-fail-under=65 -q
        language: system
        pass_filenames: false
        always_run: true 