line-length = 88
target-version = "py310"
exclude = ["site", "htmlcov"]

# Ignore vendored / generated / env directories
extend-exclude = [
    ".venv",
    "dist",
    "build",
]

[per-file-ignores]
"src/ice_cli/**/*.py" = ["E402", "F811", "F821"]
"tests/observability/*.py" = ["F401", "F403", "F821"]