"""demo_chain – generated by Chain Builder"""

from __future__ import annotations

from typing import List

from ice_orchestrator.script_chain import ScriptChain
from ice_sdk.models.node_models import AiNodeConfig, ToolNodeConfig
from ice_sdk.tools.builtins.deterministic import SumTool

nodes: List[AiNodeConfig | ToolNodeConfig] = [
    AiNodeConfig(
        id="n0",
        type="ai",
        name="mynode",
        model="",
        prompt="# TODO",
        llm_config={"provider": "openai"},
        dependencies=[],
        retries=0,
        timeout=0,
        use_cache=True,
    ),
    AiNodeConfig(
        id="n1",
        type="ai",
        name="",
        model="",
        prompt="# TODO",
        llm_config={"provider": "openai"},
        dependencies=["n0"],
        retries=0,
        timeout=0,
        use_cache=True,
    ),
]

if __name__ == "__main__":
    chain = ScriptChain(
        nodes=nodes,
        tools=[SumTool()],
        name="demo_chain",
        persist_intermediate_outputs=True,
    )
    import asyncio
    import rich

    rich.print(asyncio.run(chain.execute()).model_dump())
