# docker-compose.itest.yml
services:
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--save", "", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  api:
    # In CI this should be a prebuilt image; locally you can swap to `build:` if you want.
    image: ${IMAGE_REPO}/iceosv1a-api:${IMAGE_TAG:-dev}
    depends_on:
      - redis
    ports:
      - "8000:8000"
    volumes:
      - api_data:/app/data
    env_file:
      - config/dev.env.example
      - env.ci
    environment:
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
      REDIS_CLIENT_NAME: ${REDIS_CLIENT_NAME:-ice_api}
      REDIS_DECODE_RESPONSES: ${REDIS_DECODE_RESPONSES:-1}
      REDIS_SOCKET_TIMEOUT: ${REDIS_SOCKET_TIMEOUT:-5.0}
      REDIS_SOCKET_CONNECT_TIMEOUT: ${REDIS_SOCKET_CONNECT_TIMEOUT:-3.0}
      REDIS_MAX_CONNECTIONS: ${REDIS_MAX_CONNECTIONS:-100}
      CHAT_TTL_SECONDS: ${CHAT_TTL_SECONDS:-2592000}
      EXECUTION_TTL_SECONDS: ${EXECUTION_TTL_SECONDS:-604800}
      ORG_BUDGET_USD: ${ORG_BUDGET_USD:-5.00}
      ICE_API_TOKEN: ${ICE_API_TOKEN:-dev-token}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ICEOS_PLUGIN_MANIFESTS: ${ICEOS_PLUGIN_MANIFESTS:-/app/packs/first_party_tools/plugins.v0.yaml}
      ICE_ENABLE_WASM: ${ICE_ENABLE_WASM:-"0"}
      CONTEXT_STORE_BACKEND: ${CONTEXT_STORE_BACKEND:-redis}
      ICE_STRICT_SERIALIZATION: ${ICE_STRICT_SERIALIZATION:-1}
    command:
      ["uvicorn", "ice_api.main:app", "--host", "0.0.0.0", "--port", "8000", "--timeout-keep-alive", "5", "--limit-concurrency", "100"]
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "python - <<'PY'\nimport urllib.request,sys\ntry:\n  with urllib.request.urlopen('http://localhost:8000/api/v1/meta/registry/health', timeout=3) as r:\n    data = r.read()\n    sys.exit(0 if b'tools_count' in data else 1)\nexcept Exception:\n  sys.exit(1)\nPY",
        ]
      interval: 10s
      timeout: 3s
      retries: 30

  itest:
    # Prebuilt “test” image that already has pytest + code under /app
    image: ${IMAGE_REPO}/iceosv1a-itest:${IMAGE_TAG:-dev}
    depends_on:
      api:
        condition: service_healthy
    # If tests call http://127.0.0.1:8000, share API network namespace
    network_mode: "service:api"
    environment:
      PYTHONPATH: /app/src:/app
      ICE_STRICT_SERIALIZATION: ${ICE_STRICT_SERIALIZATION:-1}
      ICEOS_PLUGIN_MANIFESTS: /app/packs/first_party_tools/plugins.v0.yaml
      ICE_ENABLE_WASM: ${ICE_ENABLE_WASM:-"0"}
      ICE_SKIP_STRESS: ${ICE_SKIP_STRESS:-"1"}
      REDIS_URL: redis://redis:6379/0
      PYTEST_ADDOPTS: ${PYTEST_ADDOPTS:-"-p no:xdist --timeout=300 -q"}
    env_file:
      - env.ci
    command: ["bash", "-lc", "pytest -c config/testing/pytest.ini tests/integration -q"]

volumes:
  redis_data:
  api_data:
