services:
  api:
    # Use staging env; reference values from host environment or secret store
    env_file: []
    environment:
      ICE_API_TOKEN: ${ICE_API_TOKEN}
      ICEOS_RUN_MIGRATIONS: ${ICEOS_RUN_MIGRATIONS:-0}
      ICEOS_REQUIRE_DB: ${ICEOS_REQUIRE_DB:-0}
      DATABASE_URL: ${DATABASE_URL}
      ALEMBIC_SYNC_URL: ${ALEMBIC_SYNC_URL}
      SUPABASE_JWKS_URL: ${SUPABASE_JWKS_URL}
      SUPABASE_JWT_ISSUER: ${SUPABASE_JWT_ISSUER}
      SUPABASE_JWT_AUDIENCE: ${SUPABASE_JWT_AUDIENCE:-authenticated}
      ICEOS_EMBEDDINGS_PROVIDER: ${ICEOS_EMBEDDINGS_PROVIDER:-hash}
      ICE_SKIP_EXTERNAL: ${ICE_SKIP_EXTERNAL:-1}
      # Staging defaults for MCP/tool execution
      ICE_MCP_DEFAULT_TIMEOUT: ${ICE_MCP_DEFAULT_TIMEOUT:-90}
      ICE_TOOL_DEFAULT_TIMEOUT_SECONDS: ${ICE_TOOL_DEFAULT_TIMEOUT_SECONDS:-90}
      ICE_TOOL_DEFAULT_RETRIES: ${ICE_TOOL_DEFAULT_RETRIES:-1}
