services:
  redis:
    image: docker.io/redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 2s
      retries: 10

  api:
    image: "${IMAGE_REPO:-ghcr.io/stef-writes/iceos}/iceosv1a-api:${IMAGE_TAG:-${GITHUB_SHA}}"
    pull_policy: always
    env_file:
      - env.ci
    depends_on:
      - redis
    ports:
      - "8000:8000"

  itest:
    image: "${IMAGE_REPO:-ghcr.io/stef-writes/iceos}/iceosv1a-itest:${IMAGE_TAG:-${GITHUB_SHA}}"
    pull_policy: always
    environment:
      PYTHONPATH: src
      PYTEST_ADDOPTS: "-n 1 --maxfail=1 -k 'not heavy'"
    depends_on:
      - api
      - redis
    command: ["pytest", "-c", "config/testing/pytest.ini", "tests/integration", "-q"]
    network_mode: host
