gantt
    title Workflow Execution Timeline
    dateFormat X
    axisFormat %L
    section Tool
    arxiv_search_node : 0, 1000000
    section General
    market_intelligence_agent : 1000100, 2000100
    neuroscience_researcher : 2000200, 3000200
    market_intelligence_agent : 3000300, 4000300
    investment_coordinator : 4000400, 5000400