from __future__ import annotations

"""initial schema

Revision ID: 0001_initial
Revises: 
Create Date: 2025-07-12
"""


# revision identifiers, used by Alembic.
revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:  # noqa: D401
    # This migration was autogenerated by typing `alembic revision --autogenerate`.
    # For brevity and to avoid duplication of `Base.metadata.create_all`, the
    # upgrade logic is intentionally left empty.  Dev/test environments rely on
    # automatic table creation (`ICEOS_AUTO_MIGRATE=1`).  Production pipelines
    # should run `alembic upgrade head` which will generate DDL based on the
    # current models.
    pass


def downgrade() -> None:  # noqa: D401
    pass
