version: "3.9"
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "yes"]

  api:
    image: your/iceos:latest
    depends_on: [redis]
    ports:
      - "8000:8000"
    environment:
      # Core
      ICE_API_TOKEN: ${ICE_API_TOKEN:-dev-token}
      OPENAI_API_KEY: ${OPENAI_API_KEY}

      # Redis (dev default – adjust for prod)
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
      REDIS_CLIENT_NAME: ${REDIS_CLIENT_NAME:-ice_api}
      REDIS_DECODE_RESPONSES: ${REDIS_DECODE_RESPONSES:-1}
      REDIS_SOCKET_TIMEOUT: ${REDIS_SOCKET_TIMEOUT:-5.0}
      REDIS_SOCKET_CONNECT_TIMEOUT: ${REDIS_SOCKET_CONNECT_TIMEOUT:-3.0}
      REDIS_MAX_CONNECTIONS: ${REDIS_MAX_CONNECTIONS:-100}
      REDIS_SSL_CA_CERTS: ${REDIS_SSL_CA_CERTS:-}

      # Optional Sentinel (set instead of REDIS_URL)
      REDIS_SENTINEL_ENDPOINTS: ${REDIS_SENTINEL_ENDPOINTS:-}
      REDIS_SENTINEL_MASTER_NAME: ${REDIS_SENTINEL_MASTER_NAME:-}

      # Data retention
      CHAT_TTL_SECONDS: ${CHAT_TTL_SECONDS:-2592000}
      EXECUTION_TTL_SECONDS: ${EXECUTION_TTL_SECONDS:-604800}

    command: ["uvicorn", "ice_api.main:app", "--host", "0.0.0.0", "--port", "8000"]
