line-length = 88
target-version = "py310"
exclude = ["site", "htmlcov"]

# Ignore import-at-top-level rule across repo (legacy modules still reordering)
ignore = ["E402"]

# Ignore vendored / generated / env directories
extend-exclude = [
    ".venv",
    "dist",
    "build",
    "tests",
    "use_cases",
]

[lint]
# File-specific ignores (using new Ruff 0.4+ table)
[lint.per-file-ignores]
"src/ice_cli/**/*.py" = ["E402", "F811", "F821"]
"tests/observability/*.py" = ["F401", "F403", "F821"]
"alembic/env.py" = ["E402", "F821"]
"tests/**/*.py" = ["E402"]
"scripts/ci/check_tool_scaffold.py" = ["E402"]
"scripts/run_migrations.py" = ["E402"]
"src/ice_api/api/mcp.py" = ["F811"]
"scripts/verify_dead_code.py" = ["F841"]
"src/ice_orchestrator/context/graph_analyzer.py" = ["E741"]
"src/ice_orchestrator/execution/wasm_executor.py" = ["F821", "F841"]
"src/ice_orchestrator/graph/dependency_graph.py" = ["E722", "F841"]
"src/ice_orchestrator/memory/episodic.py" = ["E722"]
"src/ice_orchestrator/validation/chain_validator.py" = ["F821"]
"tests/integration/ice_api/test_mcp_models.py" = ["F841"]
"tests/integration/ice_core/test_architectural_boundaries.py" = ["F841"]
"tests/integration/test_working_patterns.py" = ["F401"]
"tests/run_memory_tests.py" = ["F841"]
"tests/unit/ice_core/registry/test_prompt_template_registry.py" = ["F841"]
"tests/unit/ice_orchestrator/execution/test_recursive_flows.py" = ["E712"]
"tests/unit/ice_orchestrator/graph/test_enhanced_networkx.py" = ["E712"]
"use_cases/RivaRidge/FB_Marketplace_Seller/agents/pricing_agent.py" = ["F841"]
"use_cases/RivaRidge/FB_Marketplace_Seller/tools/facebook_publisher.py" = ["E741"]
"src/ice_orchestrator/workflow.py" = ["F841"]

[lint.isort]
known-first-party = ["ice_core", "ice_orchestrator", "ice_builder", "ice_cli", "ice_client", "ice_tools"]

# Ban Python str.format in critical runtime paths to prevent brace-collapsing.
# Ruff's banned-api does not support glob-scoped modules here; we ban use globally
# and rely on per-file ignores if needed.
[lint.flake8-tidy-imports]
ban-relative-imports = "parents"

[[lint.flake8-tidy-imports.banned-api]]
name = "builtins.str.format"
msg = "Do not use str.format() for prompts/args; use Jinja-only rendering via resolve_jinja_templates/render_prompt."
