name: CI - Integration

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'Dockerfile'
      - 'docker-compose.itest.yml'
      - 'Makefile'

jobs:
  integration:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run integration tests (docker-compose)
        env:
          IMAGE_REPO: local
          IMAGE_TAG: dev
          ICE_ENABLE_WASM: '0'
          ICE_SKIP_STRESS: '1'
        run: make ci-integration
