name: ci-integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_REPO: ghcr.io/stef-writes/iceos
  IMAGE_TAG: ${{ github.sha }}

jobs:
  integration:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push api image
        run: |
          docker buildx build --target api --push \
            --tag $IMAGE_REPO/iceosv1a-api:$IMAGE_TAG \
            --tag $IMAGE_REPO/iceosv1a-api:main \
            --cache-from type=gha --cache-to type=gha,mode=max .

      - name: Build & push itest image
        run: |
          docker buildx build --target test --push \
            --tag $IMAGE_REPO/iceosv1a-itest:$IMAGE_TAG \
            --tag $IMAGE_REPO/iceosv1a-itest:main \
            --cache-from type=gha --cache-to type=gha,mode=max .

      - name: Run integration tests (compose)
        env:
          IMAGE_REPO: ${{ env.IMAGE_REPO }}
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        run: |
          docker compose -f docker-compose.itest.yml up \
            --abort-on-container-exit --exit-code-from itest
