name: CI - WASM (optional)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'Dockerfile'
      - 'docker-compose.itest.yml'
      - 'Makefile'

jobs:
  wasm:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build API image (api target)
        uses: docker/build-push-action@v6
        with:
          context: .
          target: api
          tags: local/iceosv1a-api:dev
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build itest image (test target)
        uses: docker/build-push-action@v6
        with:
          context: .
          target: test
          tags: local/iceosv1a-itest:dev
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run WASM tests (optional lane)
        env:
          IMAGE_REPO: local
          IMAGE_TAG: dev
          ICE_ENABLE_WASM: '1'
          ICE_SKIP_STRESS: '1'
        run: |
          make ci-wasm || echo "WASM lane non-blocking: ignoring failures"
