name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit_and_type:
    name: Lint, Type, Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker info
        run: |
          docker version
          docker info

      - name: Lint + Type + Unit Tests + Coverage Gate
        run: |
          make ci
          make test-coverage COV_MIN=85

  integration:
    name: Integration Tests (docker-compose.itest)
    needs: unit_and_type
    runs-on: ubuntu-latest
    env:
      IMAGE_REPO: local
      IMAGE_TAG: dev
      ICE_SKIP_STRESS: 1
      ICE_ENABLE_WASM: 0
      ICEOS_EMBEDDINGS_PROVIDER: hash
      ICEOS_RUN_MIGRATIONS: 1
      ICEOS_REQUIRE_DB: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker info
        run: |
          docker version
          docker info

      - name: Build API and test images (with cache)
        run: |
          docker buildx build \
            --load \
            --cache-from type=gha,scope=api \
            --cache-to type=gha,scope=api,mode=max \
            --target api -t ${IMAGE_REPO}/iceosv1a-api:${IMAGE_TAG} .
          docker buildx build \
            --load \
            --cache-from type=gha,scope=itest \
            --cache-to type=gha,scope=itest,mode=max \
            --target test -t ${IMAGE_REPO}/iceosv1a-itest:${IMAGE_TAG} .

      - name: Run docker compose itest
        run: make ci-integration
