name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit_and_type:
    name: Lint, Type, Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker info
        run: |
          docker version
          docker info

      - name: Lint + Type + Unit Tests
        run: make ci

  integration:
    name: Integration Tests (docker-compose.itest)
    needs: unit_and_type
    runs-on: ubuntu-latest
    env:
      IMAGE_REPO: local
      IMAGE_TAG: dev
      ICE_SKIP_STRESS: 1
      ICE_ENABLE_WASM: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker info
        run: |
          docker version
          docker info

      - name: Run docker compose itest
        run: make ci-integration
