name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build API image (cached)
        uses: docker/build-push-action@v6
        with:
          context: .
          target: api
          tags: local/iceosv1a-api:dev
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build itest image (cached)
        uses: docker/build-push-action@v6
        with:
          context: .
          target: test
          tags: local/iceosv1a-itest:dev
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Type check (Dockerized)
        run: |
          make type-check

      - name: Unit tests (reuse prebuilt itest image)
        run: |
          make test

      - name: Integration tests (single compose up)
        env:
          IMAGE_REPO: local
          IMAGE_TAG: dev
          ICE_ENABLE_WASM: 0
          ICE_SKIP_STRESS: 1
        run: |
          make ci-integration
