name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  quality-gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: 1.8.3

      - name: Install deps (+dev)
        run: |
          set -euo pipefail
          # Determine base ref to diff against
          git fetch --depth=2 origin "${GITHUB_REF}"
          BASE_SHA=$(git rev-parse HEAD^)
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            BASE_SHA="${{ github.event.pull_request.base.sha }}"
          fi
          # If pyproject changed, refresh lock once for this run
          if git diff --name-only "${BASE_SHA}"...HEAD | grep -q '^pyproject\.toml$'; then
            echo "pyproject.toml changed – refreshing lock"
            poetry lock
          fi
          poetry install --with dev --no-interaction --no-root

      - name: Run quality gate (lint + type + test)
        run: make ci

      - name: Upload coverage HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: htmlcov
          path: htmlcov
