name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10', '3.11']
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies (incl. dev)
        run: poetry install --with dev --no-interaction

      - name: Verify lockfile in sync
        run: make lock-check

      - name: Pre-commit (all files)
        run: poetry run pre-commit run --all-files --show-diff-on-failure

      - name: Quality gate (lint, type, tests)
        run: poetry run make doctor

      - name: Unit tests
        run: poetry run make test 