name: Consumer E2E Samples

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  consumer-samples:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install project deps (no dev) & build wheel
        run: |
          poetry install --no-interaction --no-root
          poetry build -f wheel
      - name: Create isolated venv & install wheel
        run: |
          python -m venv consumer_env
          source consumer_env/bin/activate
          pip install dist/*.whl
      - name: Run consumer smoke test
        run: |
          source consumer_env/bin/activate
          python scripts/ci/consumer_smoke.py 