name: docker-publish

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      IMAGE_REPO: ghcr.io/${{ github.repository_owner }}/iceos
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Sanity check GHCR reachability
        run: |
          set -e
          # DNS reachability (non-fatal)
          getent hosts ghcr.io || nslookup ghcr.io || true
          # Registry base endpoint should return 200/401/403; consider network failure as unreachable
          code=$(curl -sS -o /dev/null -w "%{http_code}" -I https://ghcr.io/v2/ || echo 000)
          echo "GHCR /v2/ status: $code"
          if [ "$code" = "000" ]; then echo "GHCR unreachable"; exit 1; fi

      - name: Login to GHCR (retry)
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 2
          max_attempts: 3
          command: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build and push API image (api stage)
        uses: docker/build-push-action@v6
        with:
          context: .
          target: api
          push: true
          tags: |
            ${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
