name: docker-publish

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      IMAGE_REPO: ghcr.io/${{ github.repository_owner }}/iceos
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Sanity check GHCR reachability
        run: |
          curl -fsSIL https://ghcr.io/token || (echo "GHCR unreachable" && exit 1)

      - name: Login to GHCR (retry)
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 2
          max_attempts: 3
          command: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build and push API image (api stage)
        uses: docker/build-push-action@v6
        with:
          context: .
          target: api
          push: true
          tags: |
            ${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
