name: Layer Boundary Enforcement
on: [push, pull_request]

jobs:
  layer-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: pip install -r scripts/requirements.txt
      - run: python scripts/check_layers.py 