name: Layer Boundary Enforcement
on: [push, pull_request]

jobs:
  layer-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      # No external Python dependencies; check_layers uses stdlib only
      - run: python scripts/check_layers.py 