name: Layer Boundary Guard

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  layer-guard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: |
          poetry install --with dev --no-interaction
      - name: Run layer boundary check
        run: |
          make structure
      - name: Type check (mypy --strict)
        run: |
          poetry run mypy --strict src
      - name: Schema drift guard
        run: |
          poetry run python scripts/ci/check_schema_drift.py
      - name: Run tests
        run: |
          make test