name: Onefile Smoke (disabled)

on:
  workflow_dispatch: {}

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker info
        run: |
          docker version
          docker info

      - name: Start one-file compose
        run: |
          export ICE_API_TOKEN=dev-token
          export ICE_ALLOW_DEV_TOKEN=1
          docker compose -f docker-compose.onefile.yml up -d --build
          for i in $(seq 1 60); do
            curl -fsS http://localhost:8000/readyz && break || sleep 1
          done

      - name: Library smoke
        run: |
          curl -fsS -H "Authorization: Bearer dev-token" -H 'Content-Type: application/json' \
            -d '{"label":"smoke","content":"ok","mime":"text/plain","org_id":"demo","user_id":"smoker"}' \
            http://localhost:8000/api/v1/library/assets | tee /tmp/resp.json
          test -s /tmp/resp.json

      - name: Tear down
        if: always()
        run: docker compose -f docker-compose.onefile.yml down -v || true
