name: Production Gate

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  preflight:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Poetry
        uses: abatilo/actions-poetry@v3.0.0
      - name: Install dependencies
        run: poetry install --with dev --no-interaction
      - name: Run production-check
        run: make production-check
      - name: Bandit security scan
        run: poetry run bandit -r src/ --severity-level high --confidence-level high 