name: Publish Images

on:
  push:
    branches: [ main ]
  release:
    types: [published]

jobs:
  publish:
    name: Build and Push to GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta (api)
        id: meta_api
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/iceos-api
            ghcr.io/${{ github.repository_owner }}/iceos-stack
          tags: |
            type=raw,value=${{ github.sha }}
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push (api + stack tags)
        uses: docker/build-push-action@v5
        with:
          context: .
          target: api
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta_api.outputs.tags }}
          labels: ${{ steps.meta_api.outputs.labels }}
